package com.adansoft.great21.dataaccess.entities;

// Generated May 8, 2015 10:59:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * AchievementConfig generated by hbm2java
 */
public class AchievementConfig implements java.io.Serializable {

	private int acheivementId;
	private String achievementAbbr;
	private String achivementDesc;
	private String uidivid;

	public AchievementConfig() {
	}

	public AchievementConfig(int acheivementId) {
		this.acheivementId = acheivementId;
	}

	public AchievementConfig(int acheivementId, String achievementAbbr,
			String achivementDesc, String uidivid) {
		this.acheivementId = acheivementId;
		this.achievementAbbr = achievementAbbr;
		this.achivementDesc = achivementDesc;
		this.uidivid = uidivid;
	}

	public int getAcheivementId() {
		return this.acheivementId;
	}

	public void setAcheivementId(int acheivementId) {
		this.acheivementId = acheivementId;
	}

	public String getAchievementAbbr() {
		return this.achievementAbbr;
	}

	public void setAchievementAbbr(String achievementAbbr) {
		this.achievementAbbr = achievementAbbr;
	}

	public String getAchivementDesc() {
		return this.achivementDesc;
	}

	public void setAchivementDesc(String achivementDesc) {
		this.achivementDesc = achivementDesc;
	}

	public String getUidivid() {
		return this.uidivid;
	}

	public void setUidivid(String uidivid) {
		this.uidivid = uidivid;
	}

}
