package com.adansoft.great21.dataaccess.entities;

// Generated Mar 9, 2015 3:06:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FriendRequest generated by hbm2java
 */
public class FriendRequest implements java.io.Serializable {

	private Long requestIdn;
	private Long requestorIdn;
	private Long receiverIdn;
	private Date requestedDate;
	private String status;

	public FriendRequest() {
	}

	public FriendRequest(Long requestorIdn, Long receiverIdn,
			Date requestedDate, String status) {
		this.requestorIdn = requestorIdn;
		this.receiverIdn = receiverIdn;
		this.requestedDate = requestedDate;
		this.status = status;
	}

	public Long getRequestIdn() {
		return this.requestIdn;
	}

	public void setRequestIdn(Long requestIdn) {
		this.requestIdn = requestIdn;
	}

	public Long getRequestorIdn() {
		return this.requestorIdn;
	}

	public void setRequestorIdn(Long requestorIdn) {
		this.requestorIdn = requestorIdn;
	}

	public Long getReceiverIdn() {
		return this.receiverIdn;
	}

	public void setReceiverIdn(Long receiverIdn) {
		this.receiverIdn = receiverIdn;
	}

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
