package com.adansoft.great21.dataaccess.entities;

// Generated Apr 22, 2015 3:08:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FriendRequest generated by hbm2java
 */
public class FriendRequest implements java.io.Serializable {

	private FriendRequestId id;
	private Long requestorIdn;
	private Date requestedDate;
	private String status;
	private Date actionedDate;

	public FriendRequest() {
	}

	public FriendRequest(FriendRequestId id) {
		this.id = id;
	}

	public FriendRequest(FriendRequestId id, Long requestorIdn,
			Date requestedDate, String status, Date actionedDate) {
		this.id = id;
		this.requestorIdn = requestorIdn;
		this.requestedDate = requestedDate;
		this.status = status;
		this.actionedDate = actionedDate;
	}

	public FriendRequestId getId() {
		return this.id;
	}

	public void setId(FriendRequestId id) {
		this.id = id;
	}

	public Long getRequestorIdn() {
		return this.requestorIdn;
	}

	public void setRequestorIdn(Long requestorIdn) {
		this.requestorIdn = requestorIdn;
	}

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getActionedDate() {
		return this.actionedDate;
	}

	public void setActionedDate(Date actionedDate) {
		this.actionedDate = actionedDate;
	}

}
