package com.adansoft.great21.dataaccess.entities;

// Generated Mar 10, 2015 11:08:35 AM by Hibernate Tools 3.4.0.CR1

/**
 * GamejoinRequest generated by hbm2java
 */
public class GamejoinRequest implements java.io.Serializable {

	private long requestId;
	private Long requestorIdn;
	private String gameInstanceId;

	public GamejoinRequest() {
	}

	public GamejoinRequest(long requestId) {
		this.requestId = requestId;
	}

	public GamejoinRequest(long requestId, Long requestorIdn,
			String gameInstanceId) {
		this.requestId = requestId;
		this.requestorIdn = requestorIdn;
		this.gameInstanceId = gameInstanceId;
	}

	public long getRequestId() {
		return this.requestId;
	}

	public void setRequestId(long requestId) {
		this.requestId = requestId;
	}

	public Long getRequestorIdn() {
		return this.requestorIdn;
	}

	public void setRequestorIdn(Long requestorIdn) {
		this.requestorIdn = requestorIdn;
	}

	public String getGameInstanceId() {
		return this.gameInstanceId;
	}

	public void setGameInstanceId(String gameInstanceId) {
		this.gameInstanceId = gameInstanceId;
	}

}
