package com.adansoft.great21.dataaccess.entities;

// Generated Feb 20, 2015 11:53:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * GamePlayers generated by hbm2java
 */
public class GamePlayers implements java.io.Serializable {

	private String gameInstanceId;
	private Integer numOfPlayers;
	private String player1Nick;
	private String player2Nick;
	private String player3Nick;
	private String player4Nick;
	private String player5Nick;
	private String player6Nick;
	private String player7Nick;
	private String player8Nick;

	public GamePlayers() {
	}

	public GamePlayers(String gameInstanceId) {
		this.gameInstanceId = gameInstanceId;
	}

	public GamePlayers(String gameInstanceId, Integer numOfPlayers,
			String player1Nick, String player2Nick, String player3Nick,
			String player4Nick, String player5Nick, String player6Nick,
			String player7Nick, String player8Nick) {
		this.gameInstanceId = gameInstanceId;
		this.numOfPlayers = numOfPlayers;
		this.player1Nick = player1Nick;
		this.player2Nick = player2Nick;
		this.player3Nick = player3Nick;
		this.player4Nick = player4Nick;
		this.player5Nick = player5Nick;
		this.player6Nick = player6Nick;
		this.player7Nick = player7Nick;
		this.player8Nick = player8Nick;
	}

	public String getGameInstanceId() {
		return this.gameInstanceId;
	}

	public void setGameInstanceId(String gameInstanceId) {
		this.gameInstanceId = gameInstanceId;
	}

	public Integer getNumOfPlayers() {
		return this.numOfPlayers;
	}

	public void setNumOfPlayers(Integer numOfPlayers) {
		this.numOfPlayers = numOfPlayers;
	}

	public String getPlayer1Nick() {
		return this.player1Nick;
	}

	public void setPlayer1Nick(String player1Nick) {
		this.player1Nick = player1Nick;
	}

	public String getPlayer2Nick() {
		return this.player2Nick;
	}

	public void setPlayer2Nick(String player2Nick) {
		this.player2Nick = player2Nick;
	}

	public String getPlayer3Nick() {
		return this.player3Nick;
	}

	public void setPlayer3Nick(String player3Nick) {
		this.player3Nick = player3Nick;
	}

	public String getPlayer4Nick() {
		return this.player4Nick;
	}

	public void setPlayer4Nick(String player4Nick) {
		this.player4Nick = player4Nick;
	}

	public String getPlayer5Nick() {
		return this.player5Nick;
	}

	public void setPlayer5Nick(String player5Nick) {
		this.player5Nick = player5Nick;
	}

	public String getPlayer6Nick() {
		return this.player6Nick;
	}

	public void setPlayer6Nick(String player6Nick) {
		this.player6Nick = player6Nick;
	}

	public String getPlayer7Nick() {
		return this.player7Nick;
	}

	public void setPlayer7Nick(String player7Nick) {
		this.player7Nick = player7Nick;
	}

	public String getPlayer8Nick() {
		return this.player8Nick;
	}

	public void setPlayer8Nick(String player8Nick) {
		this.player8Nick = player8Nick;
	}

}
