package com.adansoft.great21.dataaccess.entities;

// Generated Apr 22, 2015 3:08:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * GameStats generated by hbm2java
 */
public class GameStats implements java.io.Serializable {

	private GameStatsId id;

	public GameStats() {
	}

	public GameStats(GameStatsId id) {
		this.id = id;
	}

	public GameStatsId getId() {
		return this.id;
	}

	public void setId(GameStatsId id) {
		this.id = id;
	}

}
