package com.adansoft.great21.dataaccess.entities;

// Generated May 13, 2015 3:59:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * GamejoinRequestId generated by hbm2java
 */
public class GamejoinRequestId implements java.io.Serializable {

	private long gamerequestIdn;
	private long userId;

	public GamejoinRequestId() {
	}

	public GamejoinRequestId(long gamerequestIdn, long userId) {
		this.gamerequestIdn = gamerequestIdn;
		this.userId = userId;
	}

	public long getGamerequestIdn() {
		return this.gamerequestIdn;
	}

	public void setGamerequestIdn(long gamerequestIdn) {
		this.gamerequestIdn = gamerequestIdn;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GamejoinRequestId))
			return false;
		GamejoinRequestId castOther = (GamejoinRequestId) other;

		return (this.getGamerequestIdn() == castOther.getGamerequestIdn())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGamerequestIdn();
		result = 37 * result + (int) this.getUserId();
		return result;
	}

}
