package com.adansoft.great21.dataaccess.entities;

// Generated Feb 20, 2015 11:53:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * GameRoundResultsId generated by hbm2java
 */
public class GameRoundResultsId implements java.io.Serializable {

	private String gameRoundId;
	private String gameInstanceId;
	private String nickName;

	public GameRoundResultsId() {
	}

	public GameRoundResultsId(String gameRoundId, String gameInstanceId,
			String nickName) {
		this.gameRoundId = gameRoundId;
		this.gameInstanceId = gameInstanceId;
		this.nickName = nickName;
	}

	public String getGameRoundId() {
		return this.gameRoundId;
	}

	public void setGameRoundId(String gameRoundId) {
		this.gameRoundId = gameRoundId;
	}

	public String getGameInstanceId() {
		return this.gameInstanceId;
	}

	public void setGameInstanceId(String gameInstanceId) {
		this.gameInstanceId = gameInstanceId;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GameRoundResultsId))
			return false;
		GameRoundResultsId castOther = (GameRoundResultsId) other;

		return ((this.getGameRoundId() == castOther.getGameRoundId()) || (this
				.getGameRoundId() != null && castOther.getGameRoundId() != null && this
				.getGameRoundId().equals(castOther.getGameRoundId())))
				&& ((this.getGameInstanceId() == castOther.getGameInstanceId()) || (this
						.getGameInstanceId() != null
						&& castOther.getGameInstanceId() != null && this
						.getGameInstanceId().equals(
								castOther.getGameInstanceId())))
				&& ((this.getNickName() == castOther.getNickName()) || (this
						.getNickName() != null
						&& castOther.getNickName() != null && this
						.getNickName().equals(castOther.getNickName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getGameRoundId() == null ? 0 : this.getGameRoundId()
						.hashCode());
		result = 37
				* result
				+ (getGameInstanceId() == null ? 0 : this.getGameInstanceId()
						.hashCode());
		result = 37 * result
				+ (getNickName() == null ? 0 : this.getNickName().hashCode());
		return result;
	}

}
