package com.adansoft.great21.dataaccess.entities;

// Generated Apr 22, 2015 3:08:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * GamejoinRequest generated by hbm2java
 */
public class GamejoinRequest implements java.io.Serializable {

	private GamejoinRequestId id;
	private Long requestorIdn;
	private String gameInstanceId;
	private String gameType;
	private String gameLobby;
	private String status;

	public GamejoinRequest() {
	}

	public GamejoinRequest(GamejoinRequestId id) {
		this.id = id;
	}

	public GamejoinRequest(GamejoinRequestId id, Long requestorIdn,
			String gameInstanceId, String gameType, String gameLobby,
			String status) {
		this.id = id;
		this.requestorIdn = requestorIdn;
		this.gameInstanceId = gameInstanceId;
		this.gameType = gameType;
		this.gameLobby = gameLobby;
		this.status = status;
	}

	public GamejoinRequestId getId() {
		return this.id;
	}

	public void setId(GamejoinRequestId id) {
		this.id = id;
	}

	public Long getRequestorIdn() {
		return this.requestorIdn;
	}

	public void setRequestorIdn(Long requestorIdn) {
		this.requestorIdn = requestorIdn;
	}

	public String getGameInstanceId() {
		return this.gameInstanceId;
	}

	public void setGameInstanceId(String gameInstanceId) {
		this.gameInstanceId = gameInstanceId;
	}

	public String getGameType() {
		return this.gameType;
	}

	public void setGameType(String gameType) {
		this.gameType = gameType;
	}

	public String getGameLobby() {
		return this.gameLobby;
	}

	public void setGameLobby(String gameLobby) {
		this.gameLobby = gameLobby;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
