package com.adansoft.great21.dataaccess.entities;

// Generated Feb 20, 2015 11:53:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * RummyStats generated by hbm2java
 */
public class RummyStats implements java.io.Serializable {

	private String nickName;
	private double cash;
	private String rating;
	private Integer winPercent;

	public RummyStats() {
	}

	public RummyStats(String nickName, double cash) {
		this.nickName = nickName;
		this.cash = cash;
	}

	public RummyStats(String nickName, double cash, String rating,
			Integer winPercent) {
		this.nickName = nickName;
		this.cash = cash;
		this.rating = rating;
		this.winPercent = winPercent;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public double getCash() {
		return this.cash;
	}

	public void setCash(double cash) {
		this.cash = cash;
	}

	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public Integer getWinPercent() {
		return this.winPercent;
	}

	public void setWinPercent(Integer winPercent) {
		this.winPercent = winPercent;
	}

}
