package com.adansoft.great21.dataaccess.entities;

// Generated May 13, 2015 3:59:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserAcheivements generated by hbm2java
 */
public class UserAcheivements implements java.io.Serializable {

	private UserAcheivementsId id;
	private String status;
	private Date unlockedDate;
	private Integer progress;

	public UserAcheivements() {
	}

	public UserAcheivements(UserAcheivementsId id) {
		this.id = id;
	}

	public UserAcheivements(UserAcheivementsId id, String status,
			Date unlockedDate, Integer progress) {
		this.id = id;
		this.status = status;
		this.unlockedDate = unlockedDate;
		this.progress = progress;
	}

	public UserAcheivementsId getId() {
		return this.id;
	}

	public void setId(UserAcheivementsId id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getUnlockedDate() {
		return this.unlockedDate;
	}

	public void setUnlockedDate(Date unlockedDate) {
		this.unlockedDate = unlockedDate;
	}

	public Integer getProgress() {
		return this.progress;
	}

	public void setProgress(Integer progress) {
		this.progress = progress;
	}

}
