package com.adansoft.great21.dataaccess.entities;

// Generated Mar 9, 2015 3:06:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserNotifications generated by hbm2java
 */
public class UserNotifications implements java.io.Serializable {

	private UserNotificationsId id;
	private String notificationType;
	private Long notifierSrcKey;
	private String notificationDesc;
	private String notifiedBy;
	private String notificationStatus;
	private Date createdDate;

	public UserNotifications() {
	}

	public UserNotifications(UserNotificationsId id) {
		this.id = id;
	}

	public UserNotifications(UserNotificationsId id, String notificationType,
			Long notifierSrcKey, String notificationDesc, String notifiedBy,
			String notificationStatus, Date createdDate) {
		this.id = id;
		this.notificationType = notificationType;
		this.notifierSrcKey = notifierSrcKey;
		this.notificationDesc = notificationDesc;
		this.notifiedBy = notifiedBy;
		this.notificationStatus = notificationStatus;
		this.createdDate = createdDate;
	}

	public UserNotificationsId getId() {
		return this.id;
	}

	public void setId(UserNotificationsId id) {
		this.id = id;
	}

	public String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	public Long getNotifierSrcKey() {
		return this.notifierSrcKey;
	}

	public void setNotifierSrcKey(Long notifierSrcKey) {
		this.notifierSrcKey = notifierSrcKey;
	}

	public String getNotificationDesc() {
		return this.notificationDesc;
	}

	public void setNotificationDesc(String notificationDesc) {
		this.notificationDesc = notificationDesc;
	}

	public String getNotifiedBy() {
		return this.notifiedBy;
	}

	public void setNotifiedBy(String notifiedBy) {
		this.notifiedBy = notifiedBy;
	}

	public String getNotificationStatus() {
		return this.notificationStatus;
	}

	public void setNotificationStatus(String notificationStatus) {
		this.notificationStatus = notificationStatus;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
