package com.adansoft.great21.dataaccess.entities;

// Generated Mar 6, 2015 4:06:59 PM by Hibernate Tools 4.0.0

/**
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

	private long userId;
	private String grantedRole;

	public UserRoles() {
	}

	public UserRoles(long userId, String grantedRole) {
		this.userId = userId;
		this.grantedRole = grantedRole;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getGrantedRole() {
		return this.grantedRole;
	}

	public void setGrantedRole(String grantedRole) {
		this.grantedRole = grantedRole;
	}

}
