package com.adansoft.great21.dataaccess.entities;

// Generated Feb 20, 2015 11:53:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserAccounts generated by hbm2java
 */
public class UserAccounts implements java.io.Serializable {

	private String nickName;
	private String emailAddr;
	private String password;
	private boolean enabled;

	public UserAccounts() {
	}

	public UserAccounts(String nickName, String emailAddr, String password,
			boolean enabled) {
		this.nickName = nickName;
		this.emailAddr = emailAddr;
		this.password = password;
		this.enabled = enabled;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
