package com.adansoft.great21.dataaccess.entities;

// Generated May 13, 2015 3:59:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserAcheivementsId generated by hbm2java
 */
public class UserAcheivementsId implements java.io.Serializable {

	private long userId;
	private int achivementId;

	public UserAcheivementsId() {
	}

	public UserAcheivementsId(long userId, int achivementId) {
		this.userId = userId;
		this.achivementId = achivementId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public int getAchivementId() {
		return this.achivementId;
	}

	public void setAchivementId(int achivementId) {
		this.achivementId = achivementId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAcheivementsId))
			return false;
		UserAcheivementsId castOther = (UserAcheivementsId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getAchivementId() == castOther.getAchivementId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + this.getAchivementId();
		return result;
	}

}
