package com.adansoft.great21.dataaccess.entities;

// Generated Apr 22, 2015 3:08:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile implements java.io.Serializable {

	private long userId;
	private String firstname;
	private String lastname;
	private String country;
	private byte[] profilePic;

	public UserProfile() {
	}

	public UserProfile(long userId) {
		this.userId = userId;
	}

	public UserProfile(long userId, String firstname, String lastname,
			String country, byte[] profilePic) {
		this.userId = userId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.country = country;
		this.profilePic = profilePic;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public byte[] getProfilePic() {
		return this.profilePic;
	}

	public void setProfilePic(byte[] profilePic) {
		this.profilePic = profilePic;
	}

}
