package com.adansoft.great21.dataaccess.entities;

// Generated Mar 10, 2015 11:08:35 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile implements java.io.Serializable {

	private long userid;
	private String firstname;
	private String lastname;
	private String country;
	private byte[] profilePic;

	public UserProfile() {
	}

	public UserProfile(long userid) {
		this.userid = userid;
	}

	public UserProfile(long userid, String firstname, String lastname,
			String country, byte[] profilePic) {
		this.userid = userid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.country = country;
		this.profilePic = profilePic;
	}

	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public byte[] getProfilePic() {
		return this.profilePic;
	}

	public void setProfilePic(byte[] profilePic) {
		this.profilePic = profilePic;
	}

}
