package com.adansoft.great21.dataaccess.entities;

// Generated Apr 22, 2015 3:08:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserAcheivements generated by hbm2java
 */
public class UserAcheivements implements java.io.Serializable {

	private long userId;
	private Integer achivementId;
	private String status;

	public UserAcheivements() {
	}

	public UserAcheivements(long userId) {
		this.userId = userId;
	}

	public UserAcheivements(long userId, Integer achivementId, String status) {
		this.userId = userId;
		this.achivementId = achivementId;
		this.status = status;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Integer getAchivementId() {
		return this.achivementId;
	}

	public void setAchivementId(Integer achivementId) {
		this.achivementId = achivementId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
