package com.adansoft.great21.dataaccess.entities;

// Generated May 8, 2015 10:59:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

	private long userId;
	private String grantedRole;

	public UserRoles() {
	}

	public UserRoles(long userId, String grantedRole) {
		this.userId = userId;
		this.grantedRole = grantedRole;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getGrantedRole() {
		return this.grantedRole;
	}

	public void setGrantedRole(String grantedRole) {
		this.grantedRole = grantedRole;
	}

}
