package com.adansoft.great21.dataaccess.entities;

// Generated Mar 9, 2015 3:06:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserFriends generated by hbm2java
 */
public class UserFriends implements java.io.Serializable {

	private UserFriendsId id;
	private Long friendsIdn;
	private Date establishedDate;
	private Date expirationDate;

	public UserFriends() {
	}

	public UserFriends(UserFriendsId id, Date establishedDate,
			Date expirationDate) {
		this.id = id;
		this.establishedDate = establishedDate;
		this.expirationDate = expirationDate;
	}

	public UserFriends(UserFriendsId id, Long friendsIdn, Date establishedDate,
			Date expirationDate) {
		this.id = id;
		this.friendsIdn = friendsIdn;
		this.establishedDate = establishedDate;
		this.expirationDate = expirationDate;
	}

	public UserFriendsId getId() {
		return this.id;
	}

	public void setId(UserFriendsId id) {
		this.id = id;
	}

	public Long getFriendsIdn() {
		return this.friendsIdn;
	}

	public void setFriendsIdn(Long friendsIdn) {
		this.friendsIdn = friendsIdn;
	}

	public Date getEstablishedDate() {
		return this.establishedDate;
	}

	public void setEstablishedDate(Date establishedDate) {
		this.establishedDate = establishedDate;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

}
