package com.adansoft.great21.dataaccess.entities;

// Generated Apr 21, 2015 5:06:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserAccounts generated by hbm2java
 */
public class UserAccounts implements java.io.Serializable {

	private UserAccountsId id;
	private String nickName;
	private String password;
	private boolean enabled;
	private Date createdDate;

	public UserAccounts() {
	}

	public UserAccounts(UserAccountsId id, String nickName, String password,
			boolean enabled, Date createdDate) {
		this.id = id;
		this.nickName = nickName;
		this.password = password;
		this.enabled = enabled;
		this.createdDate = createdDate;
	}

	public UserAccountsId getId() {
		return this.id;
	}

	public void setId(UserAccountsId id) {
		this.id = id;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
