package com.adansoft.great21.dataaccess.entities;

// Generated May 13, 2015 3:59:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserMessagesId generated by hbm2java
 */
public class UserMessagesId implements java.io.Serializable {

	private long messageId;
	private int msgOrder;
	private long userId;

	public UserMessagesId() {
	}

	public UserMessagesId(long messageId, int msgOrder, long userId) {
		this.messageId = messageId;
		this.msgOrder = msgOrder;
		this.userId = userId;
	}

	public long getMessageId() {
		return this.messageId;
	}

	public void setMessageId(long messageId) {
		this.messageId = messageId;
	}

	public int getMsgOrder() {
		return this.msgOrder;
	}

	public void setMsgOrder(int msgOrder) {
		this.msgOrder = msgOrder;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserMessagesId))
			return false;
		UserMessagesId castOther = (UserMessagesId) other;

		return (this.getMessageId() == castOther.getMessageId())
				&& (this.getMsgOrder() == castOther.getMsgOrder())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMessageId();
		result = 37 * result + this.getMsgOrder();
		result = 37 * result + (int) this.getUserId();
		return result;
	}

}
