package com.adansoft.great21.dataaccess.entities;

// Generated May 8, 2015 10:59:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserNotificationsId generated by hbm2java
 */
public class UserNotificationsId implements java.io.Serializable {

	private long notificationIdn;
	private long userid;

	public UserNotificationsId() {
	}

	public UserNotificationsId(long notificationIdn, long userid) {
		this.notificationIdn = notificationIdn;
		this.userid = userid;
	}

	public long getNotificationIdn() {
		return this.notificationIdn;
	}

	public void setNotificationIdn(long notificationIdn) {
		this.notificationIdn = notificationIdn;
	}

	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserNotificationsId))
			return false;
		UserNotificationsId castOther = (UserNotificationsId) other;

		return (this.getNotificationIdn() == castOther.getNotificationIdn())
				&& (this.getUserid() == castOther.getUserid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNotificationIdn();
		result = 37 * result + (int) this.getUserid();
		return result;
	}

}
