package com.adansoft.great21.dataaccess.entities;

// Generated Feb 20, 2015 11:53:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

	private String nickName;
	private String grantedRole;

	public UserRoles() {
	}

	public UserRoles(String nickName, String grantedRole) {
		this.nickName = nickName;
		this.grantedRole = grantedRole;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getGrantedRole() {
		return this.grantedRole;
	}

	public void setGrantedRole(String grantedRole) {
		this.grantedRole = grantedRole;
	}

}
